### ISSUE TITLE
Version 0.8.3 errors with "Input string was not in a correct format" when selecting Processing Chain Preset 

### ISSUE THREAD

**Issue by Piquetage** [Seank23/MusicAnalyser#12]
Downloaded the v0.8.3 zip, ran the exe file, selected preset (any) and run into the "Input string was not in a correct format" error.

The error window also provided a stacktrace:
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at MusicAnalyser.Form1.DisplayScriptSettings(Int32 scriptIndex) in H:\Projects\source\repos\MusicAnalyser\MusicAnalyser\UI\Form1.cs:line 811
   at MusicAnalyser.UI.ScriptSelector.cbScript_SelectedIndexChanged(Object sender, EventArgs e) in H:\Projects\source\repos\MusicAnalyser\MusicAnalyser\UI\ScriptSelector.cs:line 22
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at MusicAnalyser.Form1.SetAppliedScripts(Dictionary`2 selectionDict) in H:\Projects\source\repos\MusicAnalyser\MusicAnalyser\UI\Form1.cs:line 741
   at MusicAnalyser.App.AppController.ApplyPreset(String presetName, Dictionary`2 preset) in H:\Projects\source\repos\MusicAnalyser\MusicAnalyser\App\AppController.cs:line 237
   at MusicAnalyser.Form1.cbPresets_SelectedIndexChanged(Object sender, EventArgs e) in H:\Projects\source\repos\MusicAnalyser\MusicAnalyser\UI\Form1.cs:line 900
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Seank23** [comment]
Hi, I'm not able to replicate this issue. Do you have the same issue if you add and configure the scripts manually or is it only when selecting a preset?
